<?xml version="1.0"?>


<xacro:macro name="bot" params="bot_name" xmlns:xacro="http://www.ros.org/wiki/xacro">

        <!-- Updated properties to match your robot model -->
        <xacro:property name="base_length" value="0.21"/>
        <xacro:property name="base_width"  value="0.095"/>
        <xacro:property name="base_height" value="0.045"/>
        <xacro:property name="wheel_radius" value="0.032"/>
        <xacro:property name="wheel_length" value="0.025"/>

        <!-- ========================= -->
        <!-- Base Footprint (empty)   -->
        <!-- ========================= -->
        <link name="${bot_name}_base_footprint"/>

        <!-- Fixed transform to base_link (body_link in your model) -->
        <joint name="${bot_name}_base_joint" type="fixed">
            <parent link="${bot_name}_base_footprint"/>
            <child link="${bot_name}_base_link"/>
            <origin xyz="0 0 0.02"/>
        </joint>

        <!-- =============== -->
        <!-- Base link body  -->
        <!-- =============== -->
        <link name="${bot_name}_base_link">
            <visual>
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}"/>
                </geometry>
                <origin xyz="0 0 0"/>
                <material name="${bot_name}"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}"/>
                </geometry>
                <origin xyz="0 0 0"/>
            </collision>
            <xacro:box_inertia m="1.140" x="${base_length}" y="${base_width}" z="${base_height}" 
                    o_xyz="0 0 0" o_rpy="0 0 0"/>
        </link>

        <!-- servo -->
        <joint name="${bot_name}_servo_joint" type="continuous">
            <parent link="${bot_name}_base_link"/>
            <child link="${bot_name}_servo_link"/>
            <origin xyz="0.076 0 0.03" rpy="0 0 0"/>
            <axis xyz="0 0 1"/>
        </joint>
        <link name="${bot_name}_servo_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.032 0.01 0.015"/>
                </geometry>
                <material name="accent_orange"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.032 0.01 0.015"/>
                </geometry>
            </collision>
            <xacro:box_inertia m="1.0" x="0.035" y="0.01" z="0.015" 
                    o_xyz="0 0 0" o_rpy="0 0 0"/>
        </link>

        
        <!-- ============================ -->
        <!-- Rear Wheels (Driven)        -->
        <!-- ============================ -->
        <xacro:macro name="wheel_link" params="bot_name prefix">
            <link name="${bot_name}_${prefix}_wheel_link">
                <visual>
                    <geometry>
                        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                    </geometry>
                    <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                    <material name="rubber_black"/>
                </visual>
                <collision>
                    <geometry>
                        <sphere radius="${wheel_radius}"/>
                    </geometry>
                    <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                </collision>
                <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" l="${wheel_length}" 
                                        o_xyz="0 0 0" o_rpy="${pi/2.0} 0 0"/>
            </link>
        </xacro:macro>

        <xacro:wheel_link bot_name="${bot_name}" prefix="rear_left"/>
        <xacro:wheel_link bot_name="${bot_name}" prefix="rear_right"/>
        <xacro:wheel_link bot_name="${bot_name}" prefix="front_left"/>
        <xacro:wheel_link bot_name="${bot_name}" prefix="front_right"/>


        <joint name="${bot_name}_rear_left_wheel_joint" type="continuous">
            <parent link="${bot_name}_base_link"/>
            <child link="${bot_name}_rear_left_wheel_link"/>
            <origin xyz="-0.04 ${-(base_width/2.0) - 0.016} -0.005" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>

        <joint name="${bot_name}_rear_right_wheel_joint" type="continuous">
            <parent link="${bot_name}_base_link"/>
            <child link="${bot_name}_rear_right_wheel_link"/>
            <origin xyz="-0.04 ${(base_width/2.0) + 0.016} -0.005" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>

        <joint name="${bot_name}_front_left_wheel_joint" type="continuous">
            <parent link="${bot_name}_base_link"/>
            <child link="${bot_name}_front_left_wheel_link"/>
            <origin xyz="0.04 ${-(base_width/2.0) - 0.016} -0.005" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>

        <joint name="${bot_name}_front_right_wheel_joint" type="continuous">
            <parent link="${bot_name}_base_link"/>
            <child link="${bot_name}_front_right_wheel_link"/>
            <origin xyz="0.04 ${(base_width/2.0) + 0.016} -0.005" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>


    <xacro:ir_sensor bot_name="${bot_name}"/>
    <xacro:camera_sensor bot_name="${bot_name}"/>
    <xacro:ultrasonic_sensor bot_name="${bot_name}"/>
    <xacro:gazebo_file bot_name="${bot_name}"/>
</xacro:macro>

