<?xml version="1.0"?>


<!-- <xacro:macro name="bot" params="bot_name"> -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

        <!-- Updated properties to match your robot model -->
        <xacro:property name="base_length" value="0.21"/>
        <xacro:property name="base_width"  value="0.095"/>
        <xacro:property name="base_height" value="0.045"/>
        <xacro:property name="wheel_radius" value="0.032"/>
        <xacro:property name="wheel_length" value="0.025"/>

        <!-- ========================= -->
        <!-- Base Footprint (empty)   -->
        <!-- ========================= -->
        <!-- <link name="${bot_name}_base_footprint"/> -->
        <link name="base_footprint"/>

        <!-- Fixed transform to base_link (body_link in your model) -->
        <joint name="base_joint" type="fixed">
            <parent link="base_footprint"/>
            <child link="base_link"/>
            <origin xyz="0 0 0.02"/>
        </joint>

        <!-- =============== -->
        <!-- Base link body  -->
        <!-- =============== -->
        <link name="base_link">
            <visual>
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}"/>
                </geometry>
                <origin xyz="0 0 0"/>
                <material name="body_blue">
                    <color rgba="0.09 0.46 0.71 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}"/>
                </geometry>
                <origin xyz="0 0 0"/>
            </collision>
            <xacro:box_inertia m="1.140" x="${base_length}" y="${base_width}" z="${base_height}" 
                    o_xyz="0 0 0" o_rpy="0 0 0"/>
        </link>

        <!-- servo -->
        <joint name="servo_joint" type="continuous">
            <parent link="base_link"/>
            <child link="servo_link"/>
            <origin xyz="0.076 0 0.03" rpy="0 0 0"/>
            <axis xyz="0 0 1"/>
        </joint>
        <link name="servo_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.032 0.01 0.015"/>
                </geometry>
                <material name="accent_orange">
                    <color rgba="0.95 0.47 0.14 1.0"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.032 0.01 0.015"/>
                </geometry>
            </collision>
            <xacro:box_inertia m="1.0" x="0.035" y="0.01" z="0.015" 
                    o_xyz="0 0 0" o_rpy="0 0 0"/>
        </link>

        
        <!-- ============================ -->
        <!-- Rear Wheels (Driven)        -->
        <!-- ============================ -->
        <xacro:macro name="wheel_link" params="prefix">
            <link name="${prefix}_wheel_link">
                <visual>
                    <geometry>
                        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                    </geometry>
                    <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                    <material name="rubber_black">
                        <color rgba="0.06 0.06 0.06 1.0"/>
                    </material>
                </visual>
                <collision>
                    <geometry>
                        <sphere radius="${wheel_radius}"/>
                    </geometry>
                    <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                </collision>
                <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" l="${wheel_length}" 
                                        o_xyz="0 0 0" o_rpy="${pi/2.0} 0 0"/>
            </link>
        </xacro:macro>

        <xacro:wheel_link prefix="rear_left"/>
        <xacro:wheel_link prefix="rear_right"/>
        <xacro:wheel_link prefix="front_left"/>
        <xacro:wheel_link prefix="front_right"/>


        <joint name="rear_left_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="rear_left_wheel_link"/>
            <origin xyz="-0.04 ${-(base_width/2.0) - 0.016} -0.005" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>

        <joint name="rear_right_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="rear_right_wheel_link"/>
            <origin xyz="-0.04 ${(base_width/2.0) + 0.016} -0.005" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>

        <joint name="front_left_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="front_left_wheel_link"/>
            <origin xyz="0.04 ${-(base_width/2.0) - 0.016} -0.005" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>

        <joint name="front_right_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="front_right_wheel_link"/>
            <origin xyz="0.04 ${(base_width/2.0) + 0.016} -0.005" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>


</robot>
<!-- </xacro:macro> -->

<!-- <xacro:rear_wheel_link bot_name="twix"/>
<xacro:rear_wheel_link bot_name="twirl"/> -->