<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="wheel" params="bot_name prefix invert_x invert_y">

        <link name="${bot_name}_${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <material name="rubber_black"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" l="${wheel_length}" 
                o_xyz="0 0 0" o_rpy="${pi/2.0} 0 0"/>
        </link>

        <joint name="${bot_name}_${prefix}_wheel_joint" type="continuous">
            <parent link="${bot_name}_base_link"/>
            <child link="${bot_name}_${prefix}_wheel_link"/>
            <origin xyz="${invert_x*0.04} ${invert_y*(base_width/2.0) - 0.016} -0.005" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>

    </xacro:macro>
</robot>